## Investigating Speciation

Analyse the results of the speciation parameter grid search on the initial and final populations of Pong experiment #4.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../../notebooks/speciation_grid_search_results.csv')
df.head()

   generation  threshold  disjoint_coeff  weight_coeff  n_species
0           0        1.0             1.0           1.0        618
1          49        1.0             1.0           1.5        719
2           0        1.0             1.0           2.0        790
3          49        1.0             1.0           1.0        562
4           0        1.0             1.0           1.5        725

In [3]:
conditions = ['(5 < n_species < 50)',
              '(weight_coeff > 0)',
              '(disjoint_coeff > 0)']
df.query(str.join('&', conditions))

      generation  threshold  disjoint_coeff  weight_coeff  n_species
380            0        2.5             1.0           1.0         10
381           49        2.5             1.0           1.0         11
395            0        2.5             1.5           1.0         22
396           49        2.5             1.5           1.0         22
412           49        2.5             2.0           1.0         31
...          ...        ...             ...           ...        ...
992           49        4.5             4.0           1.5         17
1004           0        4.5             4.5           1.0          7
1005          49        4.5             4.5           1.0         10
1006          49        4.5             4.5           1.5         18
1007           0        4.5             4.5           1.5         42

[85 rows x 5 columns]

In [4]:
conditions = ['(5 < n_species < 50)',
              '(weight_coeff >= 1)',
              '(disjoint_coeff >= 1)',
              '(weight_coeff > disjoint_coeff)']
df.query(str.join('&', conditions))

     generation  threshold  disjoint_coeff  weight_coeff  n_species
509           0        3.0             1.0           1.5         31
510          49        3.0             1.0           1.5         37
637           0        3.5             1.0           1.5         10
639          49        3.5             1.0           1.5         11
767           0        4.0             1.0           2.0         25
768          49        4.0             1.0           2.0         25
783           0        4.0             1.5           2.0         37
784          49        4.0             1.5           2.0         41
895           0        4.5             1.0           2.0         11
896          49        4.5             1.0           2.0         10
898          49        4.5             1.0           2.5         49
899           0        4.5             1.0           2.5         40
911           0        4.5             1.5           2.0         16
912          49        4.5             1.5           2.0         16